### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/MTC#21]
most solid alpha build I have seen in any app. I am super excited to see what you do with this. keep up the hard work! If I could give any recommendations, it would be to add both internal and external volume simultaneously into a stream. also the option to stream a screen display instead of a camera for mobile gamers. (guess you might need root access which is cool with me) once again. thanks for making this app. I will be using your alpha build soon for a stream update which is perfect! 

-Jake

**Comment by lfdversluis** [comment]
Thanks! Yeah it requires root to capture screens, which is also suggested in #15

**Comment by lfdversluis** [comment]
Decided to see "it would be to add both internal and external volume simultaneously into a stream" as a feature, reopening.

**Comment by lfdversluis** [comment]
After some consideration, internal value would make little sense as streaming your screen can only be done on rooted devices.
