### ISSUE TITLE
Camera Screen

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/MTC#24]
I love your app! the only thing that would make a huge difference is add the ability to see the chat while you stream and the ability to show both cameras at the same time so the viewers have the ability to watch you play while also seeing you in the camera.

**Comment by lfdversluis** [comment]
Feedback like that makes devs happy :+1: 
Capturing the screen requires a rooted device, see #15. The dual record has been suggested in #5. And chat while streaming in another.
